---
name: Lint Code Base (eslint)
run-name: "Lint code base (eslint) on \"${{ github.event.pull_request.title }}\" by ${{ github.actor }}"

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    name: "Lint: ESLint"
    if: |
      (contains(github.event.pull_request.labels.*.name, 'renovate') &&
        contains(github.event.pull_request.labels.*.name, 'renovate:lint')) ||
      !contains(github.event.pull_request.labels.*.name, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/init-node
        with:
          node-version: 18.x

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--cache --ext .ts,.tsx,.js,.jsx,.mdx,.vue .'
          github_token: ${{ secrets.GITHUB_TOKEN }}
