---
name: Test
run-name: "Test on \"${{ github.event.pull_request.title }}\" by ${{ github.actor }}"

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  init__node:
    name: "Initialize: node"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-node
        with:
          node-version: ${{ matrix.node-version }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-node
        with:
          node-version: 18.x

      - uses: ./.github/actions/build-and-cache

  test:
    name: "Test: spec"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-node
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/build-and-cache

      - run: yarn test:spec

  typecheck:
    name: "Test: typecheck"
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-node
        with:
          node-version: 18.x

      - run: yarn test:type

